server:
  port: 8080
  mode: debug

database:
  path: ./data.db
  wal: true

jwt:
  access_expire: 2h
  refresh_expire: 168h
  secret: ${JWT_SECRET}

jd_union:
  app_key: ${JD_APP_KEY}
  app_secret: ${JD_APP_SECRET}
  site_id: ${JD_SITE_ID}
  pid: ${JD_PID}

cashback:
  default_rate: 0.7

rate_limit:
  convert_per_minute: 10


#  JWT_SECRET=mypassword123 JD_APP_KEY=6e7a241a42a9fc5ca62847f320d0ecfa JD_APP_SECRET=6ed3591c00ee4e27af2ef18458e9ca64 JD_SITE_ID=4105746542 JD_PID=lemon go run ./cmd/server/

